name: create etcd binaries
on:
  schedule:
  - cron: "0 0 1 * *"
jobs:
  build:
    name: build artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.0'
    - name: Set GOPATH
      run: |
        echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
        echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
      shell: bash

    - name: run make
      run: make build
      shell: bash

    - uses: actions/upload-artifact@v1
      with:
        name: bin
        path: bin
